import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16 text-gray-800">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-10">Last updated: April 28, 2026</p>

      <section className="space-y-8 text-sm leading-7">
        <div>
          <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
          <p>
            By using Advora, you agree to these Terms of Service. If you do not agree,
            please do not use the service.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">2. Description of Service</h2>
          <p>
            Advora is an automated Instagram content platform designed for financial advisors.
            The service generates AI-powered post captions and images, and publishes them to
            your Instagram Business account on a schedule you define.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">3. Eligibility</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You must be at least 18 years old to use Advora</li>
            <li>You must have a valid Instagram Business or Creator account</li>
            <li>You must have admin access to a Facebook Page linked to your Instagram account</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">4. User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You are responsible for reviewing all content before it is published</li>
            <li>You must comply with Instagram&apos;s Community Guidelines and Terms of Use</li>
            <li>You must not use Advora to post misleading, harmful, or illegal content</li>
            <li>You are responsible for ensuring your financial content complies with applicable regulations</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">5. Instagram Permissions</h2>
          <p>
            By connecting your Instagram account, you authorize Advora to publish posts,
            read analytics, and manage content on your behalf. You can revoke this access
            at any time from your dashboard or from your Facebook settings.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">6. AI-Generated Content</h2>
          <p>
            Content generated by Advora is created using artificial intelligence and may not
            always be accurate, complete, or suitable for your specific audience. You are
            solely responsible for reviewing and approving all content before publication.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">7. Limitation of Liability</h2>
          <p>
            Advora is provided &quot;as is&quot; without warranties of any kind. We are not liable
            for any damages arising from the use of AI-generated content, failed posts,
            or service interruptions.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">8. Termination</h2>
          <p>
            We reserve the right to suspend or terminate accounts that violate these terms.
            You may delete your account at any time by contacting us.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">9. Contact</h2>
          <p>
            For questions about these Terms, contact us at:{" "}
            <a href="mailto:rajendernaik80@gmail.com" className="text-blue-600 underline">
              rajendernaik80@gmail.com
            </a>
          </p>
        </div>
      </section>
    </main>
  );
}
